package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func newRefreshCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "refresh",
		Short: "Rebuild STACK_CATALOG.md from all CAPABILITIES.md files",
		Long: `Scans for all CAPABILITIES.md files, parses them, and regenerates
the STACK_CATALOG.md file in the brain directory with an updated capability
index, dependency graph, and topological tiers.`,
		RunE: runRefresh,
	}
}

func runRefresh(cmd *cobra.Command, args []string) error {
	brainDir := expandHome(viper.GetString("brain_dir"))
	stackRoot := filepath.Dir(brainDir)

	components, err := DiscoverComponents(stackRoot)
	if err != nil {
		return fmt.Errorf("discovering components: %w", err)
	}

	if len(components) == 0 {
		return fmt.Errorf("no CAPABILITIES.md files found under %s", stackRoot)
	}

	// Sort by status priority then name
	statusOrder := map[string]int{
		"mature": 0, "active": 1, "stable": 2, "basic": 3, "planning": 4,
	}
	sort.Slice(components, func(i, j int) bool {
		si := statusOrder[strings.ToLower(components[i].Status)]
		sj := statusOrder[strings.ToLower(components[j].Status)]
		if si != sj {
			return si < sj
		}
		return strings.ToLower(components[i].Name) < strings.ToLower(components[j].Name)
	})

	// Build the catalog content
	var sb strings.Builder

	sb.WriteString("# Stack Catalog\n\n")
	sb.WriteString("> Auto-generated by `stack-brain refresh`. Do not edit manually.\n")
	sb.WriteString("> Source of truth is each component's `CAPABILITIES.md`.\n\n")

	// Capability Index table
	sb.WriteString("## Capability Index\n\n")
	sb.WriteString("| Component | Module | Location | Version | Status | Capabilities |\n")
	sb.WriteString("|-----------|--------|----------|---------|--------|-------------|\n")

	for _, c := range components {
		// Summarize capabilities as comma-separated tags
		var tags []string
		for _, cap := range c.Capabilities {
			tags = append(tags, cap.Tag)
		}
		tagStr := strings.Join(tags, ", ")
		if len(tagStr) > 80 {
			tagStr = tagStr[:77] + "..."
		}

		loc := c.Location
		// Shorten home dir for display
		home, _ := os.UserHomeDir()
		if strings.HasPrefix(loc, home) {
			loc = "~" + loc[len(home):]
		}

		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
			c.Name, c.Module, loc, c.Version, c.Status, tagStr))
	}

	// Dependency Graph
	sb.WriteString("\n## Dependency Graph\n\n```\n")

	edges := make(map[string][]string)
	allNames := make(map[string]bool)
	for _, c := range components {
		name := strings.ToLower(c.Name)
		allNames[name] = true
		for _, dep := range c.StackDeps {
			depName := strings.ToLower(dep)
			edges[name] = append(edges[name], depName)
			allNames[depName] = true
		}
	}

	// Print edges
	for _, c := range components {
		name := strings.ToLower(c.Name)
		deps := edges[name]
		if len(deps) == 0 {
			sb.WriteString(fmt.Sprintf("%s (leaf)\n", c.Name))
		} else {
			sb.WriteString(fmt.Sprintf("%s ──► %s\n", c.Name, strings.Join(c.StackDeps, ", ")))
		}
	}
	sb.WriteString("```\n")

	// Topological Tiers (same algorithm as dag command)
	sb.WriteString("\n## Topological Update Order\n\n")

	inDegree := make(map[string]int)
	for n := range allNames {
		inDegree[n] = 0
	}
	for name := range allNames {
		for _, dep := range edges[name] {
			if allNames[dep] {
				inDegree[name]++
			}
		}
	}

	remaining := make(map[string]bool)
	for n := range allNames {
		remaining[n] = true
	}

	level := 0
	for len(remaining) > 0 {
		var tier []string
		for n := range remaining {
			if inDegree[n] == 0 {
				tier = append(tier, n)
			}
		}

		if len(tier) == 0 {
			for n := range remaining {
				tier = append(tier, n)
			}
			sort.Strings(tier)
			sb.WriteString(fmt.Sprintf("%d. **Tier %d (cycle)**: %s\n", level+1, level, strings.Join(tier, ", ")))
			break
		}

		sort.Strings(tier)
		label := ""
		if level == 0 {
			label = " (leaves)"
		}
		sb.WriteString(fmt.Sprintf("%d. **Tier %d%s**: %s\n", level+1, level, label, strings.Join(tier, ", ")))

		for _, n := range tier {
			delete(remaining, n)
			for other := range remaining {
				for _, dep := range edges[other] {
					if dep == n {
						inDegree[other]--
					}
				}
			}
		}
		level++
	}

	// Capability Tags
	sb.WriteString("\n## Capability Tags\n\n```\n")
	var allTags []string
	tagSet := make(map[string]bool)
	for _, c := range components {
		for _, cap := range c.Capabilities {
			tag := strings.ToLower(cap.Tag)
			if !tagSet[tag] {
				tagSet[tag] = true
				allTags = append(allTags, tag)
			}
		}
	}
	sort.Strings(allTags)
	sb.WriteString(strings.Join(allTags, ", "))
	sb.WriteString("\n```\n")

	// Write the catalog
	catalogPath := filepath.Join(brainDir, "STACK_CATALOG.md")
	if err := os.WriteFile(catalogPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing catalog: %w", err)
	}

	fmt.Fprintf(os.Stderr, "✓ Refreshed %s (%d components)\n", catalogPath, len(components))
	return nil
}
